2025-07-28 14:51:52.123996+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "([*]19, '토끼', 'CHILD_NAME', 1)"; expected "(, SELECT, TABLE, VALUES"; SQL statement:
(19, '토끼', 'CHILD_NAME', 1) [42001-232]
2025-07-28 14:51:52.128997+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "([*]20, '인어공주', 'CHILD_NAME', 1)"; expected "(, SELECT, TABLE, VALUES"; SQL statement:
(20, '인어공주', 'CHILD_NAME', 1) [42001-232]
2025-07-28 14:51:52.129996+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "([*]21, '왕자', 'CHILD_NAME', 1)"; expected "(, SELECT, TABLE, VALUES"; SQL statement:
(21, '왕자', 'CHILD_NAME', 1) [42001-232]
2025-07-28 14:51:57.792332+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "([*]19, '토끼', 'CHILD_NAME', 1)"; expected "(, SELECT, TABLE, VALUES"; SQL statement:
(19, '토끼', 'CHILD_NAME', 1) [42001-232]
2025-07-28 14:51:57.794331+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "([*]20, '인어공주', 'CHILD_NAME', 1)"; expected "(, SELECT, TABLE, VALUES"; SQL statement:
(20, '인어공주', 'CHILD_NAME', 1) [42001-232]
2025-07-28 14:51:57.795331+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "([*]21, '왕자', 'CHILD_NAME', 1)"; expected "(, SELECT, TABLE, VALUES"; SQL statement:
(21, '왕자', 'CHILD_NAME', 1) [42001-232]
2025-07-28 14:52:45.660110+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "([*]19, '토끼', 'CHILD_NAME', 1)"; expected "(, SELECT, TABLE, VALUES"; SQL statement:
(19, '토끼', 'CHILD_NAME', 1) [42001-232]
2025-07-28 14:52:45.661109+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "([*]20, '인어공주', 'CHILD_NAME', 1)"; expected "(, SELECT, TABLE, VALUES"; SQL statement:
(20, '인어공주', 'CHILD_NAME', 1) [42001-232]
2025-07-28 14:52:45.662109+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "([*]21, '왕자', 'CHILD_NAME', 1)"; expected "(, SELECT, TABLE, VALUES"; SQL statement:
(21, '왕자', 'CHILD_NAME', 1) [42001-232]
2025-07-28 15:02:16.669779+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "([*]19, '토끼', 'CHILD_NAME', 1)"; expected "(, SELECT, TABLE, VALUES"; SQL statement:
(19, '토끼', 'CHILD_NAME', 1) [42001-232]
2025-07-28 15:02:16.671774+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "([*]20, '인어공주', 'CHILD_NAME', 1)"; expected "(, SELECT, TABLE, VALUES"; SQL statement:
(20, '인어공주', 'CHILD_NAME', 1) [42001-232]
2025-07-28 15:02:16.672776+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "([*]21, '왕자', 'CHILD_NAME', 1)"; expected "(, SELECT, TABLE, VALUES"; SQL statement:
(21, '왕자', 'CHILD_NAME', 1) [42001-232]
2025-07-28 15:10:02.666521+09:00 jdbc[14]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:217)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:134)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:139)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:368)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:205)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:483)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:747)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 16 more
2025-07-28 16:12:43.036026+09:00 jdbc[43]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:217)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:134)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:139)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:368)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:205)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:483)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:747)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 16 more
